language: java
env:
  global:
  - secure: e4gw3Hrp3FQVNbbC30QMtrH4BHgL0zcNvVgEPluHAIym4c0XT2JAjLQhGJTjgesJZw3HrM/2ltHtzMuZUifMsegZQRIl+9SQQTFfDddx8GKZM4AnhA0kSHZqsYgcA+gtzw8injF7oKucq9YlkenXJ6rDD6Hcbs/XXBItRmvYDSI=
  - secure: t3feznQD/aHE2X69tHBq3QBmD8I0IpnjqVPSco/iwAhBbQAlq+QXUBX0YhGnI3vP7/jvQ6OSEcpgl++3psw5bJr9vzeCOKMjl6x1zgPSXpUkNGczoTvbyt/6XYnYyB50KhWGUeLgmIMQKXiUOC5gIJOFAgH4xWw3kVgHBvIZ6i8=
  - secure: sOfajpt3u7pRW4ox+YrjDO/YCsQ5zQ9WSe28nhvrf+ppnKyRNcB6dKOE9ntnJ/fvukvK3BTolotryW2F+KjgK6diPpxeRAyQbY5F68t8pROe8hHcRsoO8/kSmPTKrwH0U1tVGVvavUoBcS5QA6bkym1qpl2/kNAmtk7uimeV2O0=
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_8dafc9c32687_key -iv $encrypted_8dafc9c32687_iv
  -in gpg.tar.enc -out gpg.tar -d
- tar xvf gpg.tar
install: mvn install -DskipTests=true -V
script: mvn test
after_success:
- mvn deploy -Pdeploy -DskipTests=true --settings ./settings.xml
