language: java
dist: trusty

env:
  global:
  - secure: "BqBMBEhuc+ez5JybegeWOQdIUXl9ibGXtD+2XAulYPNfn6TH+BUG/wOTZ8Bg8B0NmpOhVBUIV1PWaPvauEsQQitx46usJFvMZVv6ib3uJDKnukjSYDFGNvHrB8fZW5droBrZX67q6Po11yo9Y+p87+F7F/XTX+I+IYtXtHF/24w="
  - secure: "O2GNEjxPAVF93YXiHy6Fi5Zja8oucTH1IwjS4JgWJ4S+ATYEW3Zj3BTh47H2mTFp+Mzzix69J6nUUswShgFCqfxhqltRIGxMdWiG7QkzpXp09mW73QyY455jwntqbfJ/wmxn/TSyctBRFgtQd4au5sp66IP5Bn9MFEIuEplRP2A="
  - secure: "EzlNI9LT87qoX/xKDaBo0O60pMAR3+8fMznZtQmf7ZXAb14Gkbjo0A8GR0E4PZqJM/8/ThtzrQ6rPo1rL+rHCqeJNpQmYLUA5WQNLH5PmjJOM2hOuQjRhKMQ8KamjGm6W5otO6N3KK00OEOeB9rsPRr3nvbFqZyz/pkv/X9EeuE="

jdk:
- openjdk8

cache:
  directories:
  - $HOME/.m2

install: mvn clean install -DskipTests=true -V -U
#script: mvn test -Dkumuluzee.plugin.test.skip=true

after_success:
# Deploy to OSSHR
- if [[ $TRAVIS_PULL_REQUEST == "false" && ($TRAVIS_BRANCH == "master" || $TRAVIS_TAG) ]]; then
    openssl aes-256-cbc -K $encrypted_2d0b19d1e06d_key -iv $encrypted_2d0b19d1e06d_iv -in gpg.tar.gz.enc -out gpg.tar.gz -d;
    tar xvf gpg.tar.gz;
    mvn source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
  fi
