name: KumuluzEE CI

on: [push, pull_request]

jobs:
  test:
    name: Build and test
    runs-on: 'ubuntu-latest'

    strategy:
      matrix:
        java-version: ['11', '17', '18']

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install
        run: mvn --show-version --update-snapshots --batch-mode clean install -DskipTests=true

      - name: Test
        run: mvn --batch-mode test

  publish:
    name: Publish to OSSRH
    runs-on: 'ubuntu-latest'

    needs: test
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Restore GPG keys
        env:
          GPG_KEY: ${{ secrets.OSSRH_GPG_KEY }}
          GPG_PUB: ${{ secrets.OSSRH_GPG_PUB }}
        run: 'printf "$GPG_KEY" | base64 --decode > "$GITHUB_WORKSPACE/gpg.key" && printf "$GPG_PUB" | base64 --decode > "$GITHUB_WORKSPACE/gpg.pub" && gpg --batch --import "$GITHUB_WORKSPACE/gpg.pub" "$GITHUB_WORKSPACE/gpg.key"'

      - name: Publish to OSSRH
        env:
          OSSRH_USERNAME: Kumuluz
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
        run: mvn --batch-mode source:jar javadoc:jar deploy -Pdeploy -DskipTests=true --settings ./settings.xml;
